algoritmo "semnome"
// Função :
// Autor :
// Data : 08/01/2023
// Seção de Declarações 
var
   N1, N2 , N3: inteiro
inicio
// Seção de Comandos 
   N1 <- 0
   N2 <- 0
   
   escreva("Informe o primeiro número: ")
   leia(N1)
   escreva("Informe o segundo número: ")
   leia(N2)
   
   N3 <- N1 + N2
   
   se N1 > 0
         escreva("A soma de N1(",N1,") e N2(",N2,") é: ",N3)
   senao
         escreva("Desculpe, o resultado noa sera mostrado!")
   
fimalgoritmo
