algoritmo "semnome"
// Função :
// Autor :
// Data : 15/01/2023
// Seção de Declarações 
var
   N1, CONTADOR: inteiro
inicio

      escreval("[ DIGITE UM NÚMERO PARA EXIBIR SUA CONTAGEM ]")
      escreva("NÚMERO INFORMADO: ")
      leia(N1)

      CONTADOR <- 0
      
      enquanto CONTADOR <= N1 faca
          escreval("->", CONTADOR)
          CONTADOR <- CONTADOR + 1
      fimenquanto
      escreval("FIM DA CONTAGEM !")
      
fimalgoritmo
